### ISSUE TITLE
aiobotocore API has changed

### ISSUE THREAD

**Issue by mkatgert** [HDFGroup/hsds#110]
When building the docker image from the master branch I ran into the issue that aiobotocore recently has seen the release of version 2.0, in which the API has changed a bit: get_session() is not in __init__.py anymore but it has moved to aiobotocore.session.  See the [docs](https://aiobotocore.readthedocs.io/en/latest/)

This gives an issue, because the Dockerfile installs the latest version of aiobotocore, and the server code imports get_session from the main package and not from aiobotocore.session. The containers fail to start because of this issue.

Possible solutions would be to convert imports (a lot of them) or to pin to version 1.4.2 of aiobotocore.

**Comment by jreadey** [comment]
This should be fixed with the above merge.  Thanks @benfre!
