### ISSUE TITLE
Azure marketplace image needs quickstart instructions

### ISSUE THREAD

**Issue by bgc-autumn** [HDFGroup/hsds#114]
I am attempting to evaluate HSDS as a potential replacement for our swamp of zarrs.  My first stop was the Azure Marketplace HSDS image.  I have no idea what I have running here -- there are relevant command available in /usr/local/bin/, but nothing seems to be running, and I don't know what is left to do to get it going.  It would be extremely useful to have a quickstart document tailored to the marketplace VM.

FWIW, all of the following commands have null results:
- `docker ps`  -- no containers running
- `ps xa | grep hs` -- no processes running with "hs" in the name
- `nc localhost 80` -- nothing on port 80

I've attempted to follow the quickstart instructions fromthe README.md, but none of the scripts referenced exist, and I'm pretty sure the intent isn't to have me start from scratch.  It would be much better from an evaluation perspective if instantiating the marketplace image resulted in a minimally functioning placeholder demo.

**Comment by jreadey** [comment]
Hey - when you log in to the instance, you should see a motd: "Run '$ sudo hsds_install' to install or update the HDF Server (HSDS)".

The hsds_install script will walk you through the configuration and install needed components.

Please update this issue if you have any problems.

**Comment by bgc-autumn** [comment]
Excellent, that helped a lot!  I will point out that the MOTD is tacked onto the end of 28 lines of boilerplate, making it very easy to miss.  It would've helped if there were a comment in the Azure section of the README, or maybe even a comment at the end of the Marketplace description.

Another thought: since hsds_install appears to insist on creating a new storage account anyhow, you might consider automatically putting the tall.h5 in an appropriate location in it -- that would get me to a provably functional system with the minimum of user interaction.

Thanks again!

**Comment by jreadey** [comment]
Good points, let me see what I can do to make this more clear.
There is this doc: https://github.com/HDFGroup/hsds/blob/master/docs/post_install.md which goes over some of things you may want to do once you have the server up and running.  

There should be an option to select from an existing storage account in the setup page.  I'll verify that next time I do an install.

I'll close this issue, but feel free to open a new issue or post to the HDF forum if you have other questions/comments.
