### ISSUE TITLE
CI tests fail due to missing requirements

### ISSUE THREAD

**Issue by bilalshaikh42** [HDFGroup/hsds#143]
The ci is failing when running tests due to pip packages not being installed. The workflow should be modified to install the required packages first

**Comment by lkurz** [comment]
the python-packages.yml workflow allows for the use of a requirements.txt
add a requirements.txt file

**Comment by bilalshaikh42** [comment]
yup, on the todo list!

**Comment by jreadey** [comment]
thanks @lkurz - didn't know you were watching the HSDS live issue stream...
