### ISSUE TITLE
Return group creation properties on GET request to group

### ISSUE THREAD

**Issue by mattjala** [HDFGroup/hsds#213]
The HDF5 specification expects a group that is closed and re-opened to maintain its group creation properties. Right now, because HSDS does not return the creation properties of a group, this functionality can't be implemented in any application that uses HSDS (in my specific case, the REST VOL). 

An implementation similar to how a Dataset item returns the `creationProperties` field (https://github.com/HDFGroup/hdf-rest-api/blob/master/DatasetOps/GET_Dataset.md#creationproperties) would solve the problem.

Implementing the actual functionality of each creation property might not make sense for HSDS in particular, but it would be good not to lose the information.

**Comment by jreadey** [comment]
I've checked in a first pass for this here: https://github.com/HDFGroup/hsds/commit/e05975589c66ff55de641f9cc9baca787bf48059.

**Comment by jreadey** [comment]
Merged into master.
