### ISSUE TITLE
Support for H5D_CONTIGUOUS / H5D_COMPACT chunk layouts

### ISSUE THREAD

**Issue by mattjala** [HDFGroup/hsds#218]
Right now several VOL tests regarding DCPLs fail due to HSDS not supporting `H5D_CONTIGUOUS` or `H5D_COMPACT` chunk layouts. The specific origin of the error response is in [validateChunkLayout](https://github.com/HDFGroup/hsds/blob/b6abe006fc8636ae4f16d684f4dedbe3f41e4b12/hsds/dset_sn.py#L222) in `dset_sn.py`

**Comment by jreadey** [comment]
Merged into master.
