### ISSUE TITLE
swapped arguments for HTTPRequestEntityTooLarge

### ISSUE THREAD

**Issue by assaron** [HDFGroup/hsds#221]
I noticed that the arguments for `HTTPRequestEntityTooLarge` are swapped in the code.  I didn't find any documentation entry, but from the code https://github.com/aio-libs/aiohttp/blob/edd49b5c445b1b325e483a70bdf2635d6b72f64f/aiohttp/web_exceptions.py#L365 the arguments for `HTTPRequestEntityTooLarge` is first max size and then actual size. However, in `hsds` code it's called in the inverse order, e.g. here: https://github.com/HDFGroup/hsds/blob/master/hsds/chunk_sn.py#L631

**Comment by assaron** [comment]
Sorry, I didn't properly specify, but there are two other lines with the same problem:
https://github.com/HDFGroup/hsds/blob/master/hsds/chunk_sn.py#L1096  and https://github.com/HDFGroup/hsds/blob/master/hsds/chunk_sn.py#L1633 These are the only two as far as I can tell.

**Comment by jreadey** [comment]
Thanks @assaron .  I've pushed a fix for the other two in the chunkreffix branch.
I'll close this once I merge with master.

**Comment by mattjala** [comment]
chunkreffix was merged in #226 ; closing.
