### ISSUE TITLE
Creating Server and Running Tests

### ISSUE THREAD

**Issue by Zoe-Fehlau-ES** [HDFGroup/hsds#228]
I believe I am following the Quick Start guide correctly for a Windows 10 computer, but when I run the `python testall.py`, I get failures:

![image](https://github.com/HDFGroup/hsds/assets/126720849/fc22a365-32c4-432c-8d35-781238b6f5a0)

**Comment by jreadey** [comment]
I just built and ran on Windows10 with the latest HSDS release, and didn't have any problems with the test script.

Is your ROOT_DIR environment correct?  I.e. if you do: `c:\> dir %ROOT_DIR%`, what do you get?

**Comment by mattjala** [comment]
Closing this for now - if the issue still exists, please open a new PR and share what `c:\> dir %ROOT_DIR%` outputs.
