### ISSUE TITLE
[Question] Storage buckets supported by HSDS service

### ISSUE THREAD

**Issue by AboPlus** [HDFGroup/hsds#238]
Hello,

I have a small question that I would like to ask. Besides S3 and Azure, does the HSDS service support any other storage buckets, such as Tencent COS?

**Comment by jreadey** [comment]
It hasn't been test extensively, but I haven't had any problems with it.  There's an install guide here: https://github.com/HDFGroup/hsds/blob/master/docs/docker_install_tencent.md.

Most cloud storage implementations (other than Azure) support the s3 api, so by and large it should "just work".

**Comment by AboPlus** [comment]
Thank you very much for your response! I will try to install HSDS based on the documentation you provided. Thank you again for your response!
