### ISSUE TITLE
Cannot run ./build.sh file

### ISSUE THREAD

**Issue by annacheyette** [HDFGroup/hsds#256]
I am trying to install hsds using the ./build.sh file. After cloning the repository and navigating into the hsds folder *`cd hsds`), I've run `./build.sh`, which results in: 

```
running pyflakes on hsds
pyflakes errors in hsds...
./pyflakes.sh: line 26: pyflakes: command not found
./pyflakes.sh: line 26: pyflakes: command not found
./pyflakes.sh: line 26: pyflakes: command not found
./pyflakes.sh: line 26: pyflakes: command not found
```

**Comment by jreadey** [comment]
You'll need to do a `pip install pyflakes` before running `./build.sh`.
PyFlakes is a Python linter - there's no reason for people who aren't modifying the code to run it.  Probably best if I make this optional in the build script.

**Comment by jreadey** [comment]
I've updated the quick start section of the README to use: `./build.sh --nolint`.  This will avoid needing to install pyflakes.
