### ISSUE TITLE
Compound Type Subsetting

### ISSUE THREAD

**Issue by mattjala** [HDFGroup/hsds#280]

**Comment by mattjala** [comment]
This is already implemented within HSDS, it just needs to be handled correctly from the client's side.

**Comment by jreadey** [comment]
Are you talking about retrieving a certain set of fields from a comound type dataset?  Don't believe this is handled by HSDS.

**Comment by mattjala** [comment]
> Are you talking about retrieving a certain set of fields from a comound type dataset? Don't believe this is handled by HSDS.

Yes. I believe HSDS currently handle a request to read a subset of fields correctly, but not a request to write to a subset of fields.

**Comment by mattjala** [comment]
Implemented in #292
