### ISSUE TITLE
Incompatibility with aiobotocore v0.12.0

### ISSUE THREAD

**Issue by t20100** [HDFGroup/hsds#33]
There is an API break in version `0.12.0` of `aiobotocore`: the `get_session` function no longer takes a `loop` argument.
This makes `hsds` not working with it.

**Comment by jreadey** [comment]
I've fixed this here: https://github.com/HDFGroup/hsds/commit/8316b816b00670a2f7d5f239191bc026bcb028b8 by just taking out the loop argument - I don't think there's any effective difference.

Also took the opportunity to update all the packages and move to python 3.8.
Note that the base docker image is now hdfgroup/python:3.8 (I've pushed this to docker hub).
