### ISSUE TITLE
Creation timestamps lack resolution on Windows

### ISSUE THREAD

**Issue by mattjala** [HDFGroup/hsds#344]
`time.time()` is used to get the current time when creating a link or other object. This works fine on POSIX systems, but on Windows only has a precision of about ~16ms. This means that two subsequently created objects can have the same creation time. Sorting links by creation order no longer consistently returns the link that was actually created first.

This issue shows up when testing `H5Lget_link_name_by_idx` through the REST VOL on Windows - see [here](https://github.com/HDFGroup/vol-rest/blob/1930a61102556d71c11e3237463e26871c576dad/test/test_rest_vol.c#L12796).

We could potentially use an external library for getting the UNIX time to have enough precision on all systems.

**Comment by jreadey** [comment]
What does the HDF5 library do on Windows?

**Comment by mattjala** [comment]
The library [tries to use](https://github.com/HDFGroup/hdf5/blob/8642ed481c280c322ba619afc671ffe1d49a32e6/src/H5timer.c#L138) more precise time functions (`clock_gettime`, `gettimeofday`) before falling back to `time`.

I'm working on a PR which uses `time.perf_counter()` to make sure subsequent calls have different timestamps
