### ISSUE TITLE
Cannot keep another pod in same space as the one running hsds

### ISSUE THREAD

**Issue by Akshay-Thakare** [HDFGroup/hsds#54]
Hi,

I observed that the following line throws an error if we have any pod apart from hsds running in our namespace
https://github.com/HDFGroup/hsds/blob/master/hsds/basenode.py#L305

Kindly look into the same.

Thanks,
Akshay

**Comment by jreadey** [comment]
Does this update fix the issue: https://github.com/HDFGroup/hsds/commit/6cc3a032d07fbb1380ee3360c89cf5f052c8fcc1?

**Comment by Akshay-Thakare** [comment]
Issue fixed. Thank you.
