### ISSUE TITLE
Update travis.yml to Python 3.8

### ISSUE THREAD

**Issue by s004pmg** [HDFGroup/hsds#57]
See #44, I believe that this might be introducing some errant pyflakes messages because of the mismatch.

**Comment by jreadey** [comment]
Ah - I had moved to Python 3.8 on my desktop but didn't do a "pip install pyflakes --upgrade", so I wasn't seeing the pyflakes warning.

I've submitted a fix for the pyflakes issues: https://github.com/HDFGroup/hsds/commit/3a5cb35d580cc4b837d2b2eeb0741632540d0f26, and travis seems happy.
