### ISSUE TITLE
hsdshdflab.hdfgroup.org not answering?

### ISSUE THREAD

**Issue by vjcitn** [HDFGroup/hsds#89]
use of hsls returns

HTTPConnectionPool(host='hsdshdflab.hdfgroup.org', port=80): Max retries exceeded with url: /domains (Caused by ResponseError('too many 503 error responses'))

**Comment by jreadey** [comment]
HDFLab is done temporarily while we move to a new AWS account.  We'll post an update here: https://www.hdfgroup.org/hdfkitalab/ when it's back online.

**Comment by jreadey** [comment]
HDFLab is back up & updated with the latest lab, hsds, and h5pyd versions.
