### ISSUE TITLE
Create or update the OpenAPI specification for the api

### ISSUE THREAD

**Issue by bilalshaikh42** [HDFGroup/hsds#91]
Hello,

Would it be possible to include an updated OpenAPI Specification for the Highly Scalable Data Service? This would allow us to use the various tools in the OpenAPI ecosystem for things like input validation, (de)serialization, and to generate code for langauge other than python. For example, see the typsecript client library that we have created [here](https://www.npmjs.com/package/@biosimulations/hdf5apiclient)

I know this issue likely is not best suited for this repository. I created it originally in the hdf-rest-api repository, though it seems it is not active. Here is the [issue](https://github.com/HDFGroup/hdf-rest-api/issues/4) and the associated [PR](https://github.com/HDFGroup/hdf-rest-api/pull/5)  that I created if it is better to move discussion there.

Context
I am working on the [BioSimulations](https://github.com/biosimulations/biosimulations) project, an NIH funded academic project to enable researchers to reproduce and reuse biological simulations. We would like to use the HSDS as a backend for storing our simulation results, as it provides a great interface for querying and accessing the data stored on the cloud.

I was hoping to use the OpenAPI definitions for the hdf-rest-api to generate typescript client code that can be integrated into our existing web services. A first draft of such a library is linked above.

**Comment by jreadey** [comment]
Hi, the hdf-rest-api repo has been on pause for a while, but we are now actively working on the rest api specification.
That being the case, I'll close this issue and we can continue the discussion in the hdf-rest-api repo.
